parameters:
#    nmkd_pdf.example.class: NMKD\Bundle\PdfBundle\Example

services:
#    nmkd_pdf.example:
#        class: %nmkd_pdf.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
